### Register a new user
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "userName": "testuser",
    "password": "testpass123"
}

### Login with credentials
GET http://localhost:5000/api/user/login?username=testuser&password=testpass123

### Get all users
GET http://localhost:5000/api/user/users 